DROP TABLE IF EXISTS crawl_log CASCADE;
DROP TABLE IF EXISTS video_score CASCADE;
DROP TABLE IF EXISTS keyword_mapping CASCADE;
DROP TABLE IF EXISTS keyword_trend CASCADE;
DROP TABLE IF EXISTS category_trend CASCADE;
DROP TABLE IF EXISTS comment_sentiment CASCADE;
DROP TABLE IF EXISTS video_sentiment CASCADE;
DROP TABLE IF EXISTS video_comment CASCADE;
DROP TABLE IF EXISTS video CASCADE;
DROP TABLE IF EXISTS creator_account CASCADE;
DROP TABLE IF EXISTS channel CASCADE;
DROP TABLE IF EXISTS account_interest CASCADE;
DROP TABLE IF EXISTS account2 CASCADE;

CREATE TABLE account2 (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    bio TEXT,
    profile_image_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE account_interest (
    id SERIAL PRIMARY KEY,
    account_id INT NOT NULL,
    interest VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_account_interest_unique UNIQUE (account_id, interest)
);

CREATE TABLE channel (
    channel_id VARCHAR(100) PRIMARY KEY,
    platform VARCHAR(50) DEFAULT 'youtube',
    title VARCHAR(255),
    description TEXT,
    country VARCHAR(50),
    subscriber_count BIGINT,
    view_count BIGINT,
    video_count INT,
    created_at TIMESTAMP,
    crawled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE creator_account (
    account_id VARCHAR(100),
    platform VARCHAR(50),
    display_name VARCHAR(255),
    username VARCHAR(255),
    profile_url VARCHAR(500),
    description TEXT,
    country VARCHAR(50),
    follower_count BIGINT,
    post_count BIGINT,
    last_updated_at TIMESTAMP,
    crawled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(account_id, platform)
);

CREATE TABLE video (
    video_id VARCHAR(100) PRIMARY KEY,
    channel_id VARCHAR(100),
    platform VARCHAR(50) DEFAULT 'youtube',
    title VARCHAR(500),
    description TEXT,
    tags TEXT,
    category_id INT,
    published_at TIMESTAMP,
    duration VARCHAR(20),
    view_count BIGINT,
    like_count BIGINT,
    comment_count BIGINT,
    thumbnail_url VARCHAR(500),
    crawled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE video_comment (
    comment_id VARCHAR(100) PRIMARY KEY,
    video_id VARCHAR(100),
    platform VARCHAR(50) DEFAULT 'youtube',
    author VARCHAR(255),
    content TEXT,
    like_count INT,
    published_at TIMESTAMP
);

CREATE TABLE video_sentiment (
    video_id VARCHAR(100) PRIMARY KEY,
    platform VARCHAR(50) DEFAULT 'youtube',
    category VARCHAR(100),
    trend_score DECIMAL(5,4),
    sentiment_label VARCHAR(50),
    sentiment_score DECIMAL(5,4),
    keywords TEXT,
    summary TEXT,
    analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comment_sentiment (
    comment_id VARCHAR(100) PRIMARY KEY,
    platform VARCHAR(50) DEFAULT 'youtube',
    sentiment_label VARCHAR(50),
    sentiment_score DECIMAL(5,4),
    analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE keyword_trend (
    keyword VARCHAR(100),
    date DATE,
    platform VARCHAR(50),
    search_volume INT,
    search_volume_prev BIGINT,
    video_count INT,
    video_count_prev INT,
    avg_sentiment DECIMAL(5,4),
    avg_trend DECIMAL(5,4),
    avg_total_score DECIMAL(6,3),
    growth_rate DECIMAL(18,4),
    rank INT,
    PRIMARY KEY(keyword, date, platform)
);

CREATE TABLE category_trend (
    category VARCHAR(100),
    date DATE,
    platform VARCHAR(50),
    video_count INT,
    video_count_prev INT,
    avg_sentiment DECIMAL(5,4),
    avg_trend DECIMAL(5,4),
    avg_total_score DECIMAL(6,3),
    search_volume BIGINT,
    search_volume_prev BIGINT,
    growth_rate DECIMAL(18,4),
    rank INT,
    PRIMARY KEY(category, date, platform)
);

CREATE TABLE keyword_mapping (
    mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    video_id VARCHAR(100),
    channel_id VARCHAR(100),
    platform VARCHAR(50) DEFAULT 'youtube',
    keyword VARCHAR(100),
    weight DECIMAL(5,4),
    CONSTRAINT pk_keyword_mapping PRIMARY KEY (video_id, keyword, platform)
);

CREATE TABLE video_score (
    video_id VARCHAR(100) PRIMARY KEY,
    platform VARCHAR(50) DEFAULT 'youtube',
    engagement_score DECIMAL(6,3),
    sentiment_score DECIMAL(6,3),
    trend_score DECIMAL(6,3),
    total_score DECIMAL(6,3),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE crawl_log (
    id BIGSERIAL PRIMARY KEY,
    target_type VARCHAR(50),
    target_id VARCHAR(100),
    status VARCHAR(50),
    message TEXT,
    crawled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
